### ISSUE TITLE
[BUG] LXD/LinuxBridge crash

### ISSUE THREAD

**Issue by Davide-DD** [eclipse/fog05#118] opened 2019-06-28 01:12 UTC
**Describe the bug**
LXD or LinuxBridge (2 different outcomes encountered) crashes when creating 2 LXD containers connected through a ELAN (with DHCP). 

**To Reproduce**
1. Add network
2. Onboard 1st and 2nd container
3. Define 1st and 2nd container
4. Configure 1st and 2nd container (if it happens here, it's LXD who crashes: situation 1)
5. Start 1st and 2nd container
6. Stop 1st and 2nd container
7. Clean 1st and 2nd container (if it happens here, it's LinuxBridge who crashes: situation 2)
I'm attaching all the files I used except for the images because they're too big, but I think every local valid container archive should reproduce the issues I described.
[Cloud-Thing_Arch.zip](https://github.com/eclipse/fog05/files/3337163/Cloud-Thing_Arch.zip)

**Expected behavior**
I just expected to deploy the network to connect the 2 containers and make them communicate without being reachable from the outside.

**Desktop:**
 - OS: Linux Ubuntu
 - Version: 18.04.2
 - Involved plugin: LXD, LinuxBridge

**Additional context**
I'm currently using fog05 for my master thesis and I'm learning by myself to use it, therefore I apologize in advance for the bug above for it could be as well being due to my misunderstandings and gaps of the concepts needed to properly use this tool. However, down here, there are excerpts of the logs for each situation:

1. 
`[2019-06-28 00:18:53,172] - [INFO] > < __generate_container_dict() > LXD Plugin - Container Configuration {'name': 'cc5031692-e814-4d6d-ba81-cf099b81bb50', 'profiles': ['c5031692-e814-4d6d-ba81-cf099b81bb50'], 'source': {'type': 'image', 'alias': '1e57bb0e-cb41-4b23-bca3-1fa761a83c20'}}
[2019-06-28 00:18:53,172] - [INFO] > < configure_fdu() > [ DONE ] LXD Plugin - Generating container configuration...
[2019-06-28 00:18:53,173] - [INFO] > < configure_fdu() > [ INFO ] LXD Plugin - Creating Container...
[2019-06-28 00:18:57,761] - [INFO] > < __monitor_fdu() > [ INFO ] LXD Plugin - Updating status of 1e57bb0e-cb41-4b23-bca3-1fa761a83c10
[2019-06-28 00:19:03,436] - [INFO] > < undefine_fdu() > [ INFO ] LXD Plugin - Container Name c5031692-e814-4d6d-ba81-cf099b81bb50
[2019-06-28 00:19:03,436] - [INFO] > < configure_fdu() > [ DONE ] LXD Plugin - Creating Container...
[2019-06-28 00:19:03,438] - [ERROR] > < __monitor_instance() > [ ERROR ] LXD Plugin - Stopping monitoring of Container uuid b06524af-c6ce-43c0-bafd-4dc9580a09f3 Error Yaks replied with unexpected message
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fog05-0.2.0a1-py3.6.egg/fog05/yaks_connector.py", line 983, in cb
    callback(json.loads(v.value))
  File "/etc/fos/plugins/LXD/LXD_plugin", line 1075, in __fdu_observer
    react_func(fdu_uuid)
  File "/etc/fos/plugins/LXD/LXD_plugin", line 436, in configure_fdu
    self.update_fdu_status(fdu_uuid, instance_uuid, 'CONFIGURE')
  File "/usr/local/lib/python3.6/dist-packages/fog05-0.2.0a1-py3.6.egg/fog05/interfaces/RuntimePluginFDU.py", line 137, in update_fdu_status
    record = self.connector.loc.actual.get_node_fdu(self.node, self.uuid, fdu_uuid, instance_uuid)
  File "/usr/local/lib/python3.6/dist-packages/fog05-0.2.0a1-py3.6.egg/fog05/yaks_connector.py", line 1014, in get_node_fdu
    res = self.ws.get(s)
  File "/usr/local/lib/python3.6/dist-packages/yaks-0.2.7-py3.6.egg/yaks/workspace.py", line 125, in get
    if check_reply_is_values(reply, gm):
  File "/usr/local/lib/python3.6/dist-packages/yaks-0.2.7-py3.6.egg/yaks/runtime.py", line 95, in check_reply_is_values
    if reply.mid == Message.VALUES and msg.corr_id == reply.corr_id:
AttributeError: 'NoneType' object has no attribute 'mid'`

2. 
`[2019-06-28 00:43:13,399] - [INFO] > < __port_observer() > Linux Bridge Plugin - New Action of a Port - Port Info: {'uuid': '0b573f32-76ff-44ee-8b02-9d6d49be6989', 'status': 'DESTROY', 'cp_uuid': 'bbd9595b-75c5-414c-9d9d-8811838be1f7', 'properties': {'int_name': 'cp-07489-i', 'ext_name': 'cp-07489-e', 'cp_name': 'br-cp-07489', 'start': '/var/fos/linuxbridge/create_port_br-cp-07489.sh', 'stop': '/var/fos/linuxbridge/destroy_port_br-cp-07489.sh'}}
[2019-06-28 00:43:13,399] - [INFO] > < __port_observer() > Linux Bridge Plugin - This is a remove for : {'uuid': '0b573f32-76ff-44ee-8b02-9d6d49be6989', 'status': 'DESTROY', 'cp_uuid': 'bbd9595b-75c5-414c-9d9d-8811838be1f7', 'properties': {'int_name': 'cp-07489-i', 'ext_name': 'cp-07489-e', 'cp_name': 'br-cp-07489', 'start': '/var/fos/linuxbridge/create_port_br-cp-07489.sh', 'stop': '/var/fos/linuxbridge/destroy_port_br-cp-07489.sh'}}
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fog05-0.2.0a1-py3.6.egg/fog05/yaks_connector.py", line 1124, in cb
    callback(json.loads(v.value))
  File "/etc/fos/plugins/linuxbridge/linuxbridge_plugin", line 765, in __port_observer
    self.delete_port(port_uuid)
  File "/etc/fos/plugins/linuxbridge/linuxbridge_plugin", line 352, in delete_port
    self.call_os_plugin_function('execute_command',{'command':stop_file,'blocking':True, 'external':True})
  File "/usr/local/lib/python3.6/dist-packages/fog05-0.2.0a1-py3.6.egg/fog05/interfaces/Plugin.py", line 32, in call_os_plugin_function
    self.node, fname, fparameters)
  File "/usr/local/lib/python3.6/dist-packages/fog05-0.2.0a1-py3.6.egg/fog05/yaks_connector.py", line 857, in exec_os_eval
    res = self.ws.eval(s)
  File "/usr/local/lib/python3.6/dist-packages/yaks-0.2.7-py3.6.egg/yaks/workspace.py", line 253, in eval
    if check_reply_is_values(reply, em):
  File "/usr/local/lib/python3.6/dist-packages/yaks-0.2.7-py3.6.egg/yaks/runtime.py", line 101, in check_reply_is_values
    raise RuntimeError('Yaks replied with unexpected message')
RuntimeError: Yaks replied with unexpected message`

**Comment by gabrik** [comment] 2019-06-28 06:46
Hi @Davide-DD, thanks for the notification. 
From the logs I see that you are using YAKS APIs version 0.2.7, which are bugged, ( I apologize but the correct version is not yet released in PIP).

So I guess that if you use the correct version it will work.

In order to have the latest and working version on those API you need:

- remove current YAKS API (sudo pip3 uninstall yaks -y)
- clone https://github.com/atolab/yaks-python
- switch to branch 0.2
- sudo make install

Then you can retry with your containers.

Please let me know if this solves the issue.

**Comment by Davide-DD** [comment] 2019-06-28 12:00
Thank you very much for your help, @gabrik. I re-installed YAKS as you suggested and in fact it solved the problem related to the configure step, but I still have the problem at step 7: it does not show the log I posted before anymore, but it simply remains blocked waiting for cleaning to complete. I'm attaching the new associated log: it seems to me that the problem is that when I call stop, then, automatically, a call is also made to undefine (as far as I can understand the LXD log). 

[LXD_log.txt](https://github.com/eclipse/fog05/files/3339047/LXD_log.txt)
[LinuxBridge_log.txt](https://github.com/eclipse/fog05/files/3339056/LinuxBridge_log.txt)
[Linux_log.txt](https://github.com/eclipse/fog05/files/3339061/Linux_log.txt)

**Comment by gabrik** [comment] 2019-06-28 12:16
I see @Davide-DD,  this is not the expect behaviour.

Just some information:

are you using the last version of fog05?
Can you try by replacing:

```
    cloudsid = a.fdu.define(cloud_uuid, n1)
    thingsid = a.fdu.define(thing_uuid, n1)

    input('Press enter to configure')
    a.fdu.configure(cloudsid)
    a.fdu.configure(thingsid)

    input('Press enter to run')
    a.fdu.start(cloudsid)
    a.fdu.start(thingsid)
```

with 

```
    cloudsid = a.fdu.instantiate(cloud_uuid, n1)
    thingsid = a.fdu.instantiate(thing_uuid, n1)
```

and 
```
    a.fdu.stop(cloudsid)
    a.fdu.stop(thingsid)

    input('Press enter to clean')
    a.fdu.clean(cloudsid)
    a.fdu.clean(thingsid)

    input('Press enter to undefine')
    a.fdu.undefine(cloudsid)
    a.fdu.undefine(thingsid)
```
with 

```
    a.fdu.terminate(cloudsid)
    a.fdu.terminate(thingsid)
```

And check if the behaviour is the same?

Also I guess it can also be determined by the size of the image, LXD sometimes is very slow in stopping things, but if it was stuck for like 10min this is not the case.

Thanks

**Comment by gabrik** [comment] 2019-06-28 12:42
Just as update.
I noticed that there are some typos in the logging facility, so it was not actually calling the clean, was just the wrong function name in the log.
PR #119 solves the problem with logging.

Still to verify why it is hanging

**Comment by Davide-DD** [comment] 2019-06-28 12:45
> are you using the last version of fog05?

Yes, just checked again.


> Also I guess it can also be determined by the size of the image, LXD sometimes is very slow in stopping things, but if it was stuck for like 10min this is not the case.

I re-tried now and I waited a little longer than before (> 10 mins) but nothing... I'm using local images that are ~150MB.


> Can you try by replacing and check if the behaviour is the same?

I just tried, and it seems to me to have encountered the exact same outcome than before. Here are the logs.


[Linux_log.txt](https://github.com/eclipse/fog05/files/3339212/Linux_log.txt)
[LinuxBridge_log.txt](https://github.com/eclipse/fog05/files/3339213/LinuxBridge_log.txt)
[LXD_log.txt](https://github.com/eclipse/fog05/files/3339217/LXD_log.txt)

**Comment by gabrik** [comment] 2019-06-28 12:53
Ok, thanks.

I will try to reproduce it.

I just need the version of LXD and pylxd, in order to create a similar environment

**Comment by Davide-DD** [comment] 2019-06-28 13:00
Thank you very much. Here are the info:
LXC/LXD: 3.14
pylxd: 2.2.10

**Comment by gabrik** [comment] 2019-06-28 14:13
During testing an issue emerged from your descriptors.

The field `cpu_min_freq` now should be integer, because now indicated the needed cpu speed in MHz

I was able to reproduce the bug, using a plain alpine linux image and a plain ubuntu/xenial image.

The LXD Plugins hang during cleaning.
This message is also to mantain some trace of my debugging

**Comment by gabrik** [comment] 2019-06-28 15:10
Just as trace, line blocking is: 

/etc/fos/plugins/LXD/LXD_plugin
line 467, in clean_fdu
```
    self.call_nw_plugin_function('delete_virtual_interface',{'intf_id':intf_id})
```

Function is not called for some reason

**Comment by Davide-DD** [comment] 2019-06-29 19:27
I don't know why, but while in all my test runs prior to submitting this bug the problem surfaced, now I tried to re-run the script to make other tests and it went through all the steps successfully (never happened even once before) for the most part of the attempts I made.

**Comment by gabrik** [comment] 2019-06-30 23:00
Hi @Davide-DD, I'm experencing the same behaviour, on Ubuntu 16.04 and Ubuntu 18.04.1 it works like a charm, while on 18.04.2 sometimes it just hangs.

I will try to understart why this strange behaviour, beacuse seems not come from the code itself but from some enviornment during execution

**Comment by gabrik** [comment] 2019-07-03 07:03
After some futher investigation, seems that this is related to a concurrency problem in the YAKS server/API.

This explains the almost unpredictable behaviour, will keep this Issue updated when we got more information

**Comment by gabrik** [comment] 2019-10-03 08:15
This is solved by last merge

**Closed by gabrik** 2019-10-03 08:15 UTC
Labels: bug
