### ISSUE TITLE
FIMAPI class FDU issue

### ISSUE THREAD

**Issue by zrnapoleon** [eclipse/fog05#151] opened 2019-10-10 07:20 UTC
Hello, I want to deploy lxd FDU fog05 python API, but I cant successfully list my deployed fdu. However, I can define, configure, start, stop and deletet fdu with its uuid using FIMAPI:
![image](https://user-images.githubusercontent.com/53283508/66547148-2ec4ec00-eb71-11e9-80b0-d7f42b199244.png)

OS: Ubuntu
Version 16.04
Involved plugin LXD
LXD version: 3.18

**Comment by gabrik** [comment] 2019-10-10 08:29
Hi @zrnapoleon, first thanks for reporing this,

Can you confirm you are using the lastest version of Eclipse fog05?

I have tried to reproduce your behaviour but without success.

Also I see that the documentation is not updated.

In ordert to see what is is running you have to use a different API.
See example below

```
>>> a = FIMAPI(endpoint)
# this shows the UUID of the descriptors present in the system
>>> a.fdu.list() 
['d790a23d-ee56-5645-8c8d-fb014d9c4776']
## this shows the descriptor associated with this uuid
>>> a.fdu.info('d790a23d-ee56-5645-8c8d-fb014d9c4776')
{'id': 'lxd_example_fdu', 'name': 'test_1', 'uuid': 'd790a23d-ee56-5645-8c8d-fb014d9c4776', 'image': {'uri': 'lxd://alpine/edge', 'checksum': '', 'format': ''}, 'storage': [], 'computation_requirements': {'cpu_arch': 'x86_64', 'cpu_min_freq': 0, 'cpu_min_count': 1, 'ram_size_mb': 128.0, 'storage_size_gb': 5.0}, 'hypervisor': 'LXD', 'migration_kind': 'COLD', 'interfaces': [{'name': 'eth0', 'is_mgmt': False, 'if_type': 'INTERNAL', 'mac_address': 'be:ef:be:ef:00:01', 'virtual_interface': {'intf_type': 'BRIDGED', 'vpci': 'lxdbr0', 'bandwidth': 10}}], 'io_ports': [], 'connection_points': [], 'depends_on': []}

## this shows all the fdu instances running in the system, it is a dictionary {nodeid: [instance list]}
>>> a.fdu.instance_list('*')
{'4a560914-1c3e-4966-9fa8-7f0acc903253': ['6fd0c49e-bec3-4227-be8f-d02030282879']}
## this shows all the fdu instances for a given fdu id,  it is a dictionary {nodeid: [instance list]}
>>> a.fdu.instance_list('d790a23d-ee56-5645-8c8d-fb014d9c4776')
{'4a560914-1c3e-4966-9fa8-7f0acc903253': ['6fd0c49e-bec3-4227-be8f-d02030282879']}
## this get the fdu instance information
>>> f = a.fdu.instance_info('6fd0c49e-bec3-4227-be8f-d02030282879')
>>> f.to_json()
{'uuid': '6fd0c49e-bec3-4227-be8f-d02030282879', 'fdu_id': 'd790a23d-ee56-5645-8c8d-fb014d9c4776', 'status': 'RUN', 'image': {'uri': 'lxd://alpine/edge', 'checksum': '', 'format': ''}, 'command': None, 'storage': [], 'computation_requirements': {'cpu_arch': 'x86_64', 'cpu_min_freq': 0, 'cpu_min_count': 1, 'ram_size_mb': 128.0, 'storage_size_gb': 5.0}, 'geographical_requirements': None, 'energy_requirements': None, 'hypervisor': 'LXD', 'migration_kind': 'COLD', 'configuration': None, 'interfaces': [{'name': 'eth0', 'is_mgmt': False, 'if_type': 'INTERNAL', 'mac_address': 'be:ef:be:ef:00:01', 'virtual_interface': {'intf_type': 'BRIDGED', 'vpci': 'lxdbr0', 'bandwidth': 10}, 'vintf_name': 'eth0', 'status': 'CREATE', 'phy_face': 'lxdbr0'}], 'io_ports': [], 'connection_points': [], 'depends_on': [], 'error_code': None, 'error_msg': None, 'migration_properties': None, 'hypervisor_info': {'network': {'eth0': {'hwaddr': 'be:ef:be:ef:00:01', 'addresses': [{'address': '10.206.175.62'}]}}, 'cpu': {'usage': 1029334306}, 'memory': {'usage': 3751936, 'usage_peak': 9596928, 'swap_usage': 0, 'swap_usage_peak': 0}}}
```

Please ensure you are using the latest version, as your issue should be solved by the last commit.

**Comment by zrnapoleon** [comment] 2019-10-11 10:07
Hi @gabrik , I only git pull my local repo, it's enogh or I need follow the install.md file to remove and then re-install fog05?
![image](https://user-images.githubusercontent.com/53283508/66643654-c7329d80-ec51-11e9-85b4-98cc376eeb80.png)

**Comment by gabrik** [comment] 2019-10-11 10:47
Hi @zrnapoleon, you need to reinstall as there where major changes also in the agent portion.

The installation script should work as before

**Comment by zrnapoleon** [comment] 2019-10-14 02:35
Hi @gabrik , I reinstall my 2 node, one througjh the installatoon script and the onter using the manual installation.
I can successfully start the yaks and agent, but I met a issue when iI try to run the linux plugin(same for linux_bridge and LXD)
![image](https://user-images.githubusercontent.com/53283508/66726756-c413f900-ee6d-11e9-805b-4b8155e15797.png)
It seems that there some problem for the zenoh API.

**Comment by gabrik** [comment] 2019-10-14 06:57
Hi @zrnapoleon, I guess there is some error in the builded library.

If you are using ubunu 18.04 please run this command:

```
curl -L -o /usr/local/lib/libzenohc.so https://www.dropbox.com/s/c6l18wbtk4eggpt/libzenohc.so
```

And then try to start the plugins.

**Comment by zrnapoleon** [comment] 2019-10-14 08:25
Hi @gabrik my ubuntu version is 16.04, but it works too. Thanks

**Comment by zrnapoleon** [comment] 2019-10-14 08:35
![image](https://user-images.githubusercontent.com/53283508/66737984-fd655c80-ee9f-11e9-9ee6-e8276e75f632.png)
![image](https://user-images.githubusercontent.com/53283508/66738120-56cd8b80-eea0-11e9-8bea-567332a599a1.png)

Hi @gabrik in my case:
The 'dccd...' is the uuid of fdu, and 'f4c387..' is the uuid of fdu insatance running on the node, what's the third one ('a5d1505..') correspendant? I think it should be only one fdu instance. And i check with lxc list command, it alos shows only one insance id.

**Comment by gabrik** [comment] 2019-10-14 08:58
Hi @zrnapoleon,

I see, I think the state in yaks is a little bit corrupted, can you try it by restart everything?

Maybe aftersome error an instance was still stored in yaks even if it was not present.

**Comment by zrnapoleon** [comment] 2019-10-14 09:22
Hi @gabrik ,

I have stop all everything and reboot this node, but this intance ID still stored in the yaks:
![image](https://user-images.githubusercontent.com/53283508/66740636-3a345200-eea6-11e9-896f-1f169a7be683.png)
And i deploy same fdu on the other node, it only has one instance:
![image](https://user-images.githubusercontent.com/53283508/66740745-81224780-eea6-11e9-9251-9cc6f4c95081.png)
So it means this instance only stored locally as those 2 nodes are connected to the same yaks server.
Besides, do yoy know how to remove it form the yaks storage?

**Comment by gabrik** [comment] 2019-10-14 09:57
Hi @zrnapoleon,

I guess the easy way is to use yaks api to remove that, or just restart yaks


Using yaks api:

```
$ python3
>>> from yaks import Yaks
>>> y = Yaks.login('<yaks ip>:7447')
>>> ws = y.workspace('/')
>>> r = ws.get('/**/19f959af-a40f-424b-a56d-569865c9dbe9/info')
>>> for x in r: print(x[0]) # double enter
... 
/dlfos/4a560914-1c3e-4966-9fa8-7f0acc903253/runtimes/892ae9fe-9d1b-4dc6-87a3-66f5695a9971/fdu/d790a23d-ee56-5645-8c8d-fb014d9c4776/instances/19f959af-a40f-424b-a56d-569865c9dbe9/info
/dgfos/0/tenants/0/nodes/4a560914-1c3e-4966-9fa8-7f0acc903253/fdu/d790a23d-ee56-5645-8c8d-fb014d9c4776/instances/19f959af-a40f-424b-a56d-569865c9dbe9/info
/alfos/4a560914-1c3e-4966-9fa8-7f0acc903253/runtimes/892ae9fe-9d1b-4dc6-87a3-66f5695a9971/fdu/d790a23d-ee56-5645-8c8d-fb014d9c4776/instances/19f959af-a40f-424b-a56d-569865c9dbe9/info
/agfos/0/tenants/0/nodes/4a560914-1c3e-4966-9fa8-7f0acc903253/fdu/d790a23d-ee56-5645-8c8d-fb014d9c4776/instances/19f959af-a40f-424b-a56d-569865c9dbe9/info
>>> ws.remove('/dlfos/4a560914-1c3e-4966-9fa8-7f0acc903253/runtimes/892ae9fe-9d1b-4dc6-87a3-66f5695a9971/fdu/d790a23d-ee56-5645-8c8d-fb014d9c4776/instances/19f959af-a40f-424b-a56d-569865c9dbe9/info')
>>> ws.remove('/dgfos/0/tenants/0/nodes/4a560914-1c3e-4966-9fa8-7f0acc903253/fdu/d790a23d-ee56-5645-8c8d-fb014d9c4776/instances/19f959af-a40f-424b-a56d-569865c9dbe9/info
/alfos/4a560914-1c3e-4966-9fa8-7f0acc903253/runtimes/892ae9fe-9d1b-4dc6-87a3-66f5695a9971/fdu/d790a23d-ee56-5645-8c8d-fb014d9c4776/instances/19f959af-a40f-424b-a56d-569865c9dbe9/info')
ws.remove('/alfos/4a560914-1c3e-4966-9fa8-7f0acc903253/runtimes/892ae9fe-9d1b-4dc6-87a3-66f5695a9971/fdu/d790a23d-ee56-5645-8c8d-fb014d9c4776/instances/19f959af-a40f-424b-a56d-569865c9dbe9/info')
```

But I suggest to restart yaks, because maybe there are other inconsitences in the state.

**Comment by zrnapoleon** [comment] 2019-10-16 08:42
Hi @gabrik,
I just restarted all services and reboot my nodes 2 or 3 times, and finnally remove this abnormal instance.
![image](https://user-images.githubusercontent.com/53283508/66902846-fa02da00-f033-11e9-98f5-7b7dd717b072.png)

By the way, I find that there are several API commends that not yet included in your official API doc, could you provide me the latest one if it's possible?

**Comment by gabrik** [comment] 2019-10-16 10:11
Hi @zrnapoleon,

Yes, we are on it, once #153 will be merged the documentation will be updated.

In the meanwhile I guess that looking at the examples should give you some hints on how they are supposed to be used.

**Comment by gabrik** [comment] 2019-10-24 11:00
Hi @zrnapoleon,

New documentation is now available, please refer to [README.md](https://github.com/eclipse/fog05#interact-with-the-nodes) in order to build the documentation

**Closed by gabrik** 2019-10-24 11:00 UTC
