### ISSUE TITLE
[BUG] TypeError: __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by wuwei3** [eclipse/fog05#143] opened 2019-08-13 07:33 UTC
**Describe the bug**
I copied the https://github.com/atolab/fog05_demo/blob/master/fim_api/lifecycle_nonetwork.py
and execute the file, pass the params, but get the error:

![9](https://user-images.githubusercontent.com/46955295/62922965-42f1a480-bddf-11e9-873a-b2c438036501.jpg)

Did I pass the wrong params?

**To Reproduce**
1. copy the content of https://github.com/atolab/fog05_demo/blob/master/fim_api/lifecycle_nonetwork.py
2. upload to server
3. execute the py file

**Desktop (please complete the following information):**
 - OS: Ubuntu 16
 - Version: master
 - Involved plugin: All

**Comment by gabrik** [comment] 2019-08-13 07:42
Hi @wuwei3, you are passing the right arguments I just tested it, but I cannot get the error, can you paste the content of the kvm_fdu.json file?

Because the error is in the FDU object creation

**Comment by wuwei3** [comment] 2019-08-13 07:44
[kvm_fdu.txt](https://github.com/eclipse/fog05/files/3495816/kvm_fdu.txt)

**Comment by gabrik** [comment] 2019-08-13 07:53
Thanks, from what I can see you are using a wrong descriptor, the last update modified a little bit the descriptor format
It should be like this:
```
{
    "id": "test-kvm-fdu",
    "name": "test",
    "computation_requirements": {
        "cpu_arch": "x86_64",
        "cpu_min_freq": 0,
        "cpu_min_count": 1,
        "ram_size_mb": 128,
        "storage_size_gb": 10
    },
    "image": {
        "uri": "file:///home/ubuntu/alpine.tar.gz",
        "checksum": "21f436639dda7941a26d1eb0c5427862fd19910b",
        "format": "tar.gz"
    },
    "hypervisor": "KVM",
    "migration_kind": "LIVE",
    "interfaces": [
        {
            "name": "eth0",
            "is_mgmt": false,
            "if_type": "INTERNAL",
            "mac_address": "be:ef:be:ef:00:01",
            "virtual_interface": {
                "intf_type": "VIRTIO",
                "vpci": "0:0:0",
                "bandwidth": 10
            },
            "cp_id": "fdu-cp-1"
        }
    ],
    "io_ports": [],
    "connection_points": [
        {
            "id": "fdu-cp-1",
            "name": "fdu-cp1",
            "vld_ref": "6cc2aa30-1dcf-4c93-a57e-433fd0bd498e"
        }
    ],
    "depends_on": []
}
```

Can you also check if you have the fog05-im python package installed?

```
pip3 list | grep fog05
fog05                    0.2.0
fog05-im                 0.2.0
```

Also I see that you are using a .tag.gz image with a KVM hypervisor, I think it will not work, as tipically KVM accepts image formats not compressed one, are you sure it is a KVM image and not an LXD one?

**Comment by wuwei3** [comment] 2019-08-13 08:14
Hi, 
This is the 'pip3 list | grep fog05' result

![4](https://user-images.githubusercontent.com/46955295/62925548-25273e00-bde5-11e9-9acd-21d72c37d4b0.jpg)


And  I am sorry, I don't have the KVM or LXD, so if it is not exits, it will throw error?

**Comment by gabrik** [comment] 2019-08-13 08:32
Ok, just to be sure do a `git pull` of the latest version and run
```
$ make -C src/im/python/ && sudo make -C src/im/python/ install
$ sudo make -C src/api/python/api/ install
```

If you do not have installed in the node the plugin for LXD or KVM it will not be able to instantiate the FDU.

In order to install the LXD plugin (for instance...)
```
sudo make -C fos-plugins/LXD install
```

and then edit the `/etc/fos/plugins/LXD/LXD_plugin.json" file with the correct nodeid

**Comment by wuwei3** [comment] 2019-08-14 08:50
>"image": {
>         "uri": "file:///home/ubuntu/alpine.tar.gz",
>         "checksum": "21f436639dda7941a26d1eb0c5427862fd19910b",
>         "format": "tar.gz"
>     },

for this one, if I didn't have the 'alpine.tar.gz', what will happen?

is it this error?

![4](https://user-images.githubusercontent.com/46955295/63007588-80276680-beb3-11e9-9750-9ab0c8064d1b.PNG)

**Comment by gabrik** [comment] 2019-08-14 08:54
Yes, you will have that error, in this case you can use another image, like one coming from the LXD repositiory, just using this portion as image:

```
"image": {
        "uri": "lxd://alpine/3.6",
        "checksum": "",
        "format": ""
    },

```

it will fetch the image from the LXD repository

**Comment by wuwei3** [comment] 2019-08-15 06:15
For the 
> "uri": "lxd://alpine/3.6",
you mean, this one could be run normally? I tried, it was the same error above.

Could you help me for how to get one image from remote? I mean, with the correct uri which could be run correctly. Thanks

**Comment by wuwei3** [comment] 2019-08-15 07:51
And I got another problme, 

I executed the script files in ubuntu 16:
>$ ./etc/systemd/enable
>$ ./etc/systemd/start

but, if I execute the 'lxc list', got error:

![3](https://user-images.githubusercontent.com/46955295/63080604-158a2f80-bf74-11e9-91ab-cb17580259a4.PNG)

But I get no problem in ubuntu14,

![5](https://user-images.githubusercontent.com/46955295/63080687-4ec29f80-bf74-11e9-94c7-59ff567430fb.PNG)

I don't know why.

**Comment by gabrik** [comment] 2019-08-18 14:13
All the fog05 components runs under a user called fos, that should be able to access the LXD daemon, so it should be part of the lxd group.

Can you try to run:

```
sudo -u fos lxc list
```

If you get  a connection error this means that you have to add the user to the lxd group
```
sudo usermod -aG lxd fos
```

**Comment by gabrik** [comment] 2019-08-19 16:03
@wuwei3 can you also paste the output of the LXD plugin? I'm wondering if for some reason it is unable to get the image from the LXD repo

**Comment by zrnapoleon** [comment] 2019-08-21 02:52
@gabrik Hello, wuwei3 and me work together. And I tried to run the LXD plugin by hand  in ubuntu 16 (the other 4 YAKS, Agent, Linux and Linux-bridge have been run succesully): 
sudo -u fos /etc/fos/plugins/LXD/LXD_plugin /etc/fos/plugins/LXD/LXD_plugin.json
But I got a NewConnectionError :
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=8443): Max retries exceeded with url: /1.0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0d5565b2e8>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by zrnapoleon** [comment] 2019-08-21 07:59
@gabrik And if i trt to run those plugins using Systemctl i met an error:

sudo ./etc/systemd/enable.sh 

![image](https://user-images.githubusercontent.com/53283508/63413523-76aa7b00-c42c-11e9-9ca0-da0c4472c93e.png)

**Comment by gabrik** [comment] 2019-08-21 16:07
Hi @zrnapoleon,

This seems a misconfiguration of the LXD daemon, because for some reason the plugin is unable to contact the running daemon.
I suggest first to check if there is something listening on port 8443 on localhost, if yes, then I guess that the user 'fos' is not in the lxd group.
Or you may need to remove lxd and reinstall it from snap

```
$ sudo apt remove --purge lxd
$ sudo snap remove lxd
$ sudo snap install lxd
```

**Comment by zrnapoleon** [comment] 2019-08-22 02:14
Hi @gabrik，

 I did just as you recommended but still cant enable those plugins:
 
![image](https://user-images.githubusercontent.com/53283508/63480341-1535eb00-c4c4-11e9-8ad5-00276460f245.png)

**Comment by gabrik** [comment] 2019-08-22 09:42
before starting the LXD plugin can you run:
```
$ sudo lxd init
```

Then please verify if there is something listening on port 8443 using

```

**Comment by zrnapoleon** [comment] 2019-08-22 10:01
Hi @gabrik, 
I did:
$ sudo apt remove --purge lxd
$ sudo snap remove lxd
$ sudo snap install lxd
$ sudo lxd init
![image](https://user-images.githubusercontent.com/53283508/63504902-1b988700-c505-11e9-8000-43266c77ddc7.png)

Parameters set for lxd INIT
![image](https://user-images.githubusercontent.com/53283508/63504927-28b57600-c505-11e9-9089-df1ebc187733.png)

ifconfig:
![image](https://user-images.githubusercontent.com/53283508/63505041-5d293200-c505-11e9-9247-bf0d37972ad5.png)

sudo netstat -tlpn
![image](https://user-images.githubusercontent.com/53283508/63505079-6dd9a800-c505-11e9-92cc-996d47d8358d.png)
**Nothing  listening on port 8443**

![image](https://user-images.githubusercontent.com/53283508/63505128-86e25900-c505-11e9-850b-b61c4f38113e.png)

cd fos-plugins/LXD/
sudo make install

![image](https://user-images.githubusercontent.com/53283508/63505796-c2c9ee00-c506-11e9-884d-1373ce614c0c.png)

**Comment by gabrik** [comment] 2019-08-22 10:19
Ok, I see, the problem is that LXD it is not listening on port 8443, so the plugin is not able to connect.

Can you check if it is actually running:

```
$ sudo systemctl status snap.lxd.daemon
```

And then verify that the python3 client is working:

```
$ python3
> from pylxd import Client
> c = Client()
```
Please paste any error you get

**Comment by zrnapoleon** [comment] 2019-08-23 01:40
$ sudo systemctl status snap.lxd.daemon

![image](https://user-images.githubusercontent.com/53283508/63560515-dae25180-c588-11e9-86cf-28a7f310166e.png)

python3 client
![image](https://user-images.githubusercontent.com/53283508/63560552-049b7880-c589-11e9-9183-ec869ba3f80e.png)
![image](https://user-images.githubusercontent.com/53283508/63560574-1c72fc80-c589-11e9-83cf-6000e03ea253.png)
![image](https://user-images.githubusercontent.com/53283508/63560595-31e82680-c589-11e9-817b-98e533b0db41.png)
![image](https://user-images.githubusercontent.com/53283508/63560624-42989c80-c589-11e9-938f-741bedc7afde.png)

deleted  /var/lib/lxd/unix.socket
![image](https://user-images.githubusercontent.com/53283508/63560687-7ffd2a00-c589-11e9-83e7-24b81c99f2eb.png)
python code again:
![image](https://user-images.githubusercontent.com/53283508/63560745-b6d34000-c589-11e9-8e34-ae7d1a9fc7a5.png)
![image](https://user-images.githubusercontent.com/53283508/63560760-c783b600-c589-11e9-9063-413d7bc727f6.png)

sudo -u fos /etc/fos/plugins/LXD/LXD_plugin /etc/fos/plugins/LXD/LXD_plugin.json
![image](https://user-images.githubusercontent.com/53283508/63560805-f8fc8180-c589-11e9-998a-4d962111e77d.png)

**Comment by gabrik** [comment] 2019-08-23 16:13
Ok, I see, can you try to reinstall the pylxd client.

```
$ sudo pip3 uninstall pylxd -y 
$ sudo pip3 install pylxd
```

Then probably there is a missing package for python api, which I need to fix the make file

So from the fog05 repo directory

```
$ cd /src/im/python
$ make
$ sudo make install
```

And then verify the operativity of the lxd plugin

**Comment by zrnapoleon** [comment] 2019-08-26 02:48
I sucessfully reinstalled the pylxd client. but i got a error when i install the package for python:
![image](https://user-images.githubusercontent.com/53283508/63661763-6c9ec880-c7ee-11e9-9d7e-4cb3774c39be.png)
it seams that i should install a python module "pyangbind" which has been already installed, i dont know why:
![image](https://user-images.githubusercontent.com/53283508/63661905-f353a580-c7ee-11e9-8f25-c6469ce0e09e.png)

**Comment by gabrik** [comment] 2019-08-26 06:36
Hi @zrnapoleon, I guess you have to install pyang 
```
sudo pip3 install pyang
```

And then the same steps as before to install the python package, you do not need sudo during `make`, only for `make install`

```
$ cd src/im/python
$ make
$ sudo make install
```

**Comment by zrnapoleon** [comment] 2019-08-26 07:18
![image](https://user-images.githubusercontent.com/53283508/63672340-5441a480-c814-11e9-9a74-7eb792718596.png)
yeah, i checked and found that i have already installed it
i still got the following error when i instal the package:
![image](https://user-images.githubusercontent.com/53283508/63672469-98cd4000-c814-11e9-8df9-eb6400565f8d.png)
![image](https://user-images.githubusercontent.com/53283508/63672500-a8e51f80-c814-11e9-9d42-6eefdc5c58fe.png)

**Comment by gabrik** [comment] 2019-08-26 07:19
I see, can you do a `sudo make clean` and then try the `make`

I guess there is some file with wrong permission due to the previous usage of `sudo`

**Comment by zrnapoleon** [comment] 2019-08-26 07:34
Yeah it is! 
![image](https://user-images.githubusercontent.com/53283508/63673377-bf8c7600-c816-11e9-8459-5cc9ff410282.png)

And then i should try to start the plugin manually:
sudo -u fos /etc/fos/plugins/LXD/LXD_plugin /etc/fos/plugins/LXD/LXD_plugin.json
![image](https://user-images.githubusercontent.com/53283508/63673463-df239e80-c816-11e9-9fa6-cc7b6ddf7f90.png)
![image](https://user-images.githubusercontent.com/53283508/63673506-fcf10380-c816-11e9-89e2-1e32e94fcd4e.png)

Or it still has something else need to fix before i do that?

**Comment by gabrik** [comment] 2019-08-26 07:39
This is strange, I think you have the `pyangbind` installed, can you try to execute `sudo pip3 list | grep yang`

You should get something like this:

```
$ sudo pip3 list | grep yang
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pyang (1.7.5)
pyangbind (0.8.1)
```

**Comment by zrnapoleon** [comment] 2019-08-26 07:40
Yeah, i have already instaled those 2 modules
![image](https://user-images.githubusercontent.com/53283508/63673841-cc5d9980-c817-11e9-9657-f7169e1f1d4e.png)

**Comment by gabrik** [comment] 2019-08-26 07:45
In this case I think there is something strange in the path used by python to resolve the modules.
Can you run `ls -ln /usr/bin/python3`

**Comment by zrnapoleon** [comment] 2019-08-26 07:59
ok
![image](https://user-images.githubusercontent.com/53283508/63675024-72aa9e80-c81a-11e9-8404-d64f993cb004.png)

**Comment by zrnapoleon** [comment] 2019-08-26 08:00
ok
![image](https://user-images.githubusercontent.com/53283508/63675104-9ec61f80-c81a-11e9-8796-a085dce5b9b5.png)

**Comment by gabrik** [comment] 2019-08-26 08:01
I see, and if you run `sudo -u fos ls -ln /usr/bin/python3` you get the same result? 

Because I think that they are using two different path for python modules and so it cannot find the correct module

**Comment by zrnapoleon** [comment] 2019-08-26 08:03
i think they are the same result:
![image](https://user-images.githubusercontent.com/53283508/63675282-067c6a80-c81b-11e9-8e25-21aa9e535347.png)

**Comment by gabrik** [comment] 2019-08-26 08:08
I see.
Then let's try to understand if there is something in the path
Can you `run python3 -c "import sys; print(sys.path)"` and  `sudo -u fos python3 -c "import sys; print(sys.path)"`  they should be the same

**Comment by zrnapoleon** [comment] 2019-08-26 08:11
there is a little diff:
![image](https://user-images.githubusercontent.com/53283508/63675787-2d876c00-c81c-11e9-8f25-22d98e51a86b.png)

**Comment by gabrik** [comment] 2019-08-26 08:13
Ok then in this case we can check if the pyangbind is installed in that path
`ls -ln /home/ubuntu/.local/lib/python3.6/site-packages | grep yang`

**Comment by zrnapoleon** [comment] 2019-08-26 08:16
yeah:
![image](https://user-images.githubusercontent.com/53283508/63676040-b8686680-c81c-11e9-8ac3-99172fe7424d.png)

**Comment by gabrik** [comment] 2019-08-26 08:18
Ok, I think we can try to solve this by running this:

`sudo -u fos sudo pip3 install pyangbind`

Then it should be able to install in the right path, I still do not understand why it is installed in the user python path and not system-wide

**Comment by zrnapoleon** [comment] 2019-08-26 08:30
but it  was installed in the user python path again...
![image](https://user-images.githubusercontent.com/53283508/63677020-ba332980-c81e-11e9-83f0-689fa870e44d.png)

**Comment by gabrik** [comment] 2019-08-26 08:32
Ok then, remove it and reinstall it.
```
sudo pip3 uninstall pyangbind -y
sudo pip3 install pyangbind
```

I do not know if there is a way to force pip to install system-wide, usually install with sudo should make pip aware of the usage of system-wide path

**Comment by zrnapoleon** [comment] 2019-08-27 02:10
Hi @gabrik ,

Thanks for your help and it seams that i have sucessfully started the lxd plugin:
![image](https://user-images.githubusercontent.com/53283508/63735399-480c2480-c8b2-11e9-9a06-a8574e5e7d1d.png)
but, if I execute the 'lxc list', got error, and the fos uses is inside the lxd group:
![image](https://user-images.githubusercontent.com/53283508/63735570-d680a600-c8b2-11e9-9c8d-fd5e418c816d.png)

**Comment by gabrik** [comment] 2019-08-27 06:32
Hi @zrnapoleon

Can you check which lxc client is ubuntu using?
It should return something like this:

```
$ which lxc
/snap/bin/lxc
```

Or you can try with `sudo -H -u fos lxc list`

**Comment by zrnapoleon** [comment] 2019-08-27 07:26
it returens like this:
![image](https://user-images.githubusercontent.com/53283508/63749881-f75ef080-c8de-11e9-88cb-f4f774d4bd23.png)

**Comment by gabrik** [comment] 2019-08-27 07:32
Ok then you have to remove the old client in order to use the one shiped by snap
```
$ sudo apt remove --purge lxd-client
```
and now with `which lxc` you should get the right one.

But just for your infomation it is not an issue if fos user cannot do `lxc list` as to see containers you can still use your normal account

**Comment by zrnapoleon** [comment] 2019-08-27 07:39
Yeah, for one node it works bur for the onther not:
![image](https://user-images.githubusercontent.com/53283508/63750867-d9928b00-c8e0-11e9-8d62-daee94b125aa.png)

![image](https://user-images.githubusercontent.com/53283508/63750827-c7b0e800-c8e0-11e9-9e36-467866da6987.png)

**Comment by gabrik** [comment] 2019-08-27 07:44
This things drive me crazy...

Can you try a reboot on the node that is not working and then run `lxc list` ?
It makes no sense that it knows that it has to use `/snap/bin/lxc` but it uses `/usr/bin/lxc`

**Comment by zrnapoleon** [comment] 2019-08-27 07:56
I rebooted the node then it solved. @gabrik  Thank you very much for your patience and detailed explanation.

**Comment by gabrik** [comment] 2019-08-27 08:13
Let me know if we can close this issue and in case of other problems/questions you can open other ones

**Comment by zrnapoleon** [comment] 2019-08-27 08:42
@gabrik  one more question: i dont know why each time i reboot my node, the yaksd service will start automaticlly, if i dont kill the ps, i cant do "yaksd -vv" to start the yaksd plugin manually:
![image](https://user-images.githubusercontent.com/53283508/63755483-57f32b00-c8e9-11e9-89d1-5634d6d799a5.png)
![image](https://user-images.githubusercontent.com/53283508/63755495-60e3fc80-c8e9-11e9-84e0-fc78b0b93b84.png)
and cant use systemed to start it:
![image](https://user-images.githubusercontent.com/53283508/63755614-9852a900-c8e9-11e9-8dcb-767cc6093d8e.png)

**Comment by gabrik** [comment] 2019-08-27 08:48
@zrnapoleon the `enable.sh` enables autostart of yaksd and other components.

You can run 
```
$ sudo systemctl disable yaks
$ sudo systemctl disable fos_agent
$ sudo systemctl disable fos_linux
$ sudo systemctl disable fos_linuxbridge
$ sudo systemctl disable fos_lxd
```
To disable this behaviour, then you can start it manually or using the script `start.sh`

To verify that error I guess you can run
```
$ sudo systemctl enable yaks
$ journalctl -xe
```
And copy the output so we can verify why is going in error

**Comment by zrnapoleon** [comment] 2019-08-27 08:51
![image](https://user-images.githubusercontent.com/53283508/63756400-e1efc380-c8ea-11e9-8cb7-1238a0c3fb09.png)

**Comment by gabrik** [comment] 2019-08-27 08:53
I see no errors in the output,  can also see output coming from yaksd so, I guess we can ignore that `Failed to execute operation...`

**Comment by zrnapoleon** [comment] 2019-08-27 09:10
Ok, thanks! Ithink we can close this issue and in case of other questions we can open other one.

**Closed** 2019-08-27 09:12 UTC
Labels: bug
